title: Wahidur Rahman Upal

description: >- Data Engineering and Analytics Portfolio
  
#https://github.com/wahidupal
show_excerpts: false # set to true to show excerpts on the homepage
baseurl: "/wahid-upal_portfolio" # the subpath of your site, e.g. /blog
url: "https://wahidupal.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

minima:
  date_format: "%b %-d, %Y"
  skin: dark

header_pages:
 - data_engineering.md
 - python_applications.md
 - ai_automation.md
 - PowerBI.md
 - education_research.md
 - contact.md
# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
