title: Wahidur Rahman Upal

description: >-
  Data Engineering and Analytics Portfolio

baseurl: "/wahid-upal_portfolio"
url: "https://wahidupal.github.io"

show_excerpts: false

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"
  skin: dark

header_pages:
 - Home.md
 - data_engineering.md
 - python_applications.md
 - ai_automation.md
 - PowerBI.md
 - education_research.md
 - contact.md
